jasypt:
  encryptor:
    password: arkhyterima

management:
  endpoints:
    web:
      exposure:
        include: logfile, httptrace, auditevents, loggers, env, mappings, threaddump, metrics, info

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    stream:
      bindings:
        BlogCreationInput:
          destination:  blog-creation
          content-type: application/json
        BlogApprovalOutput:
          destination:  blog-approval
          content-type: application/json
        BlogApprovalNotificationOutput:
          destination:  blog-notification
          content-type: application/json
        BlogKeyOutput:
          destination:  blog-key
          content-type: application/json
        BlogNumberPerCategoryOutput:
          destination:  blog-number-per-category
          content-type: application/json
        BlogNumberPerCategoryOutputV2:
          destination:  blog-number-per-category-v2
          content-type: application/json
        BlogApprovalStatisticOutput:
          destination:  blog-approval-statistic
          content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost